AUTHORS_DATA = [
    {
        "username": "luna.wright",
        "email": "luna.wright@example.com",
        "first_name": "Luna",
        "last_name": "Wright",
        "password": "Password123!",
    },
    {
        "username": "ethan.cole",
        "email": "ethan.cole@example.com",
        "first_name": "Ethan",
        "last_name": "Cole",
        "password": "Password123!",
    },
    {
        "username": "maya.stewart",
        "email": "maya.stewart@example.com",
        "first_name": "Maya",
        "last_name": "Stewart",
        "password": "Password123!",
    },
    {
        "username": "owen.clark",
        "email": "owen.clark@example.com",
        "first_name": "Owen",
        "last_name": "Clark",
        "password": "Password123!",
    },
    {
        "username": "harper.james",
        "email": "harper.james@example.com",
        "first_name": "Harper",
        "last_name": "James",
        "password": "Password123!",
    },
    {
        "username": "noah.bennett",
        "email": "noah.bennett@example.com",
        "first_name": "Noah",
        "last_name": "Bennett",
        "password": "Password123!",
    },
    {
        "username": "aurora.miles",
        "email": "aurora.miles@example.com",
        "first_name": "Aurora",
        "last_name": "Miles",
        "password": "Password123!",
    },
    {
        "username": "julian.reed",
        "email": "julian.reed@example.com",
        "first_name": "Julian",
        "last_name": "Reed",
        "password": "Password123!",
    },
    {
        "username": "ivy.morgan",
        "email": "ivy.morgan@example.com",
        "first_name": "Ivy",
        "last_name": "Morgan",
        "password": "Password123!",
    },
    {
        "username": "felix.hayes",
        "email": "felix.hayes@example.com",
        "first_name": "Felix",
        "last_name": "Hayes",
        "password": "Password123!",
    },
    {
        "username": "nora.foster",
        "email": "nora.foster@example.com",
        "first_name": "Nora",
        "last_name": "Foster",
        "password": "Password123!",
    },
    {
        "username": "leo.murray",
        "email": "leo.murray@example.com",
        "first_name": "Leo",
        "last_name": "Murray",
        "password": "Password123!",
    },
    {
        "username": "scarlett.holt",
        "email": "scarlett.holt@example.com",
        "first_name": "Scarlett",
        "last_name": "Holt",
        "password": "Password123!",
    },
    {
        "username": "silas.hunter",
        "email": "silas.hunter@example.com",
        "first_name": "Silas",
        "last_name": "Hunter",
        "password": "Password123!",
    },
    {
        "username": "amelia.lane",
        "email": "amelia.lane@example.com",
        "first_name": "Amelia",
        "last_name": "Lane",
        "password": "Password123!",
    },
    {
        "username": "wyatt.ellis",
        "email": "wyatt.ellis@example.com",
        "first_name": "Wyatt",
        "last_name": "Ellis",
        "password": "Password123!",
    },
    {
        "username": "violet.hart",
        "email": "violet.hart@example.com",
        "first_name": "Violet",
        "last_name": "Hart",
        "password": "Password123!",
    },
    {
        "username": "mason.griffin",
        "email": "mason.griffin@example.com",
        "first_name": "Mason",
        "last_name": "Griffin",
        "password": "Password123!",
    },
    {
        "username": "eden.bishop",
        "email": "eden.bishop@example.com",
        "first_name": "Eden",
        "last_name": "Bishop",
        "password": "Password123!",
    },
    {
        "username": "ashton.hale",
        "email": "ashton.hale@example.com",
        "first_name": "Ashton",
        "last_name": "Hale",
        "password": "Password123!",
    },
    {
        "username": "talia.sanders",
        "email": "talia.sanders@example.com",
        "first_name": "Talia",
        "last_name": "Sanders",
        "password": "Password123!",
    },
    {
        "username": "kai.dawson",
        "email": "kai.dawson@example.com",
        "first_name": "Kai",
        "last_name": "Dawson",
        "password": "Password123!",
    },
    {
        "username": "adelyn.brooks",
        "email": "adelyn.brooks@example.com",
        "first_name": "Adelyn",
        "last_name": "Brooks",
        "password": "Password123!",
    },
    {
        "username": "roman.hendrix",
        "email": "roman.hendrix@example.com",
        "first_name": "Roman",
        "last_name": "Hendrix",
        "password": "Password123!",
    },
    {
        "username": "phoebe.drake",
        "email": "phoebe.drake@example.com",
        "first_name": "Phoebe",
        "last_name": "Drake",
        "password": "Password123!",
    },
    {
        "username": "elias.rowe",
        "email": "elias.rowe@example.com",
        "first_name": "Elias",
        "last_name": "Rowe",
        "password": "Password123!",
    },
    {
        "username": "alana.knox",
        "email": "alana.knox@example.com",
        "first_name": "Alana",
        "last_name": "Knox",
        "password": "Password123!",
    },
    {
        "username": "jax.thorne",
        "email": "jax.thorne@example.com",
        "first_name": "Jax",
        "last_name": "Thorne",
        "password": "Password123!",
    },
    {
        "username": "mila.daniels",
        "email": "mila.daniels@example.com",
        "first_name": "Mila",
        "last_name": "Daniels",
        "password": "Password123!",
    },
    {
        "username": "gavin.pierce",
        "email": "gavin.pierce@example.com",
        "first_name": "Gavin",
        "last_name": "Pierce",
        "password": "Password123!",
    },
    {
        "username": "freya.harmon",
        "email": "freya.harmon@example.com",
        "first_name": "Freya",
        "last_name": "Harmon",
        "password": "Password123!",
    },
    {
        "username": "asher.todd",
        "email": "asher.todd@example.com",
        "first_name": "Asher",
        "last_name": "Todd",
        "password": "Password123!",
    },
    {
        "username": "willow.maddox",
        "email": "willow.maddox@example.com",
        "first_name": "Willow",
        "last_name": "Maddox",
        "password": "Password123!",
    },
    {
        "username": "grayson.bauer",
        "email": "grayson.bauer@example.com",
        "first_name": "Grayson",
        "last_name": "Bauer",
        "password": "Password123!",
    },
    {
        "username": "lola.kerr",
        "email": "lola.kerr@example.com",
        "first_name": "Lola",
        "last_name": "Kerr",
        "password": "Password123!",
    },
    {
        "username": "ryder.hunt",
        "email": "ryder.hunt@example.com",
        "first_name": "Ryder",
        "last_name": "Hunt",
        "password": "Password123!",
    },
    {
        "username": "isla.webb",
        "email": "isla.webb@example.com",
        "first_name": "Isla",
        "last_name": "Webb",
        "password": "Password123!",
    },
    {
        "username": "griffin.short",
        "email": "griffin.short@example.com",
        "first_name": "Griffin",
        "last_name": "Short",
        "password": "Password123!",
    },
    {
        "username": "stella.beck",
        "email": "stella.beck@example.com",
        "first_name": "Stella",
        "last_name": "Beck",
        "password": "Password123!",
    },
    {
        "username": "zane.moss",
        "email": "zane.moss@example.com",
        "first_name": "Zane",
        "last_name": "Moss",
        "password": "Password123!",
    },
    {
        "username": "elodie.roach",
        "email": "elodie.roach@example.com",
        "first_name": "Elodie",
        "last_name": "Roach",
        "password": "Password123!",
    },
    {
        "username": "caleb.frye",
        "email": "caleb.frye@example.com",
        "first_name": "Caleb",
        "last_name": "Frye",
        "password": "Password123!",
    },
    {
        "username": "serena.holt",
        "email": "serena.holt@example.com",
        "first_name": "Serena",
        "last_name": "Holt",
        "password": "Password123!",
    },
    {
        "username": "tobias.mercer",
        "email": "tobias.mercer@example.com",
        "first_name": "Tobias",
        "last_name": "Mercer",
        "password": "Password123!",
    },
    {
        "username": "sienna.floyd",
        "email": "sienna.floyd@example.com",
        "first_name": "Sienna",
        "last_name": "Floyd",
        "password": "Password123!",
    },
    {
        "username": "xavier.page",
        "email": "xavier.page@example.com",
        "first_name": "Xavier",
        "last_name": "Page",
        "password": "Password123!",
    },
    {
        "username": "adrian.sloan",
        "email": "adrian.sloan@example.com",
        "first_name": "Adrian",
        "last_name": "Sloan",
        "password": "Password123!",
    },
    {
        "username": "elara.knight",
        "email": "elara.knight@example.com",
        "first_name": "Elara",
        "last_name": "Knight",
        "password": "Password123!",
    },
    {
        "username": "blake.rowan",
        "email": "blake.rowan@example.com",
        "first_name": "Blake",
        "last_name": "Rowan",
        "password": "Password123!",
    },
    {
        "username": "nova.rich",
        "email": "nova.rich@example.com",
        "first_name": "Nova",
        "last_name": "Rich",
        "password": "Password123!",
    },
    {
        "username": "declan.overton",
        "email": "declan.overton@example.com",
        "first_name": "Declan",
        "last_name": "Overton",
        "password": "Password123!",
    },
    {
        "username": "embry.keane",
        "email": "embry.keane@example.com",
        "first_name": "Embry",
        "last_name": "Keane",
        "password": "Password123!",
    },
    {
        "username": "tessa.burns",
        "email": "tessa.burns@example.com",
        "first_name": "Tessa",
        "last_name": "Burns",
        "password": "Password123!",
    },
    {
        "username": "ryan.hurst",
        "email": "ryan.hurst@example.com",
        "first_name": "Ryan",
        "last_name": "Hurst",
        "password": "Password123!",
    },
    {
        "username": "keira.bowen",
        "email": "keira.bowen@example.com",
        "first_name": "Keira",
        "last_name": "Bowen",
        "password": "Password123!",
    },
    {
        "username": "jamie.mercer",
        "email": "jamie.mercer@example.com",
        "first_name": "Jamie",
        "last_name": "Mercer",
        "password": "Password123!",
    },
    {
        "username": "nathan.burke",
        "email": "nathan.burke@example.com",
        "first_name": "Nathan",
        "last_name": "Burke",
        "password": "Password123!",
    },
    {
        "username": "lena.cross",
        "email": "lena.cross@example.com",
        "first_name": "Lena",
        "last_name": "Cross",
        "password": "Password123!",
    },
    {
        "username": "finley.vance",
        "email": "finley.vance@example.com",
        "first_name": "Finley",
        "last_name": "Vance",
        "password": "Password123!",
    },
    {
        "username": "ariel.hicks",
        "email": "ariel.hicks@example.com",
        "first_name": "Ariel",
        "last_name": "Hicks",
        "password": "Password123!",
    },
    {
        "username": "samuel.tate",
        "email": "samuel.tate@example.com",
        "first_name": "Samuel",
        "last_name": "Tate",
        "password": "Password123!",
    },
    {
        "username": "amelie.ray",
        "email": "amelie.ray@example.com",
        "first_name": "Amelie",
        "last_name": "Ray",
        "password": "Password123!",
    },
    {
        "username": "kian.pope",
        "email": "kian.pope@example.com",
        "first_name": "Kian",
        "last_name": "Pope",
        "password": "Password123!",
    },
    {
        "username": "sylvie.sharp",
        "email": "sylvie.sharp@example.com",
        "first_name": "Sylvie",
        "last_name": "Sharp",
        "password": "Password123!",
    },
    {
        "username": "reid.gibbs",
        "email": "reid.gibbs@example.com",
        "first_name": "Reid",
        "last_name": "Gibbs",
        "password": "Password123!",
    },
    {
        "username": "athena.frost",
        "email": "athena.frost@example.com",
        "first_name": "Athena",
        "last_name": "Frost",
        "password": "Password123!",
    },
    {
        "username": "soren.blake",
        "email": "soren.blake@example.com",
        "first_name": "Soren",
        "last_name": "Blake",
        "password": "Password123!",
    },
    {
        "username": "elsie.ayers",
        "email": "elsie.ayers@example.com",
        "first_name": "Elsie",
        "last_name": "Ayers",
        "password": "Password123!",
    },
    {
        "username": "tristan.hardy",
        "email": "tristan.hardy@example.com",
        "first_name": "Tristan",
        "last_name": "Hardy",
        "password": "Password123!",
    },
    {
        "username": "ruby.sheen",
        "email": "ruby.sheen@example.com",
        "first_name": "Ruby",
        "last_name": "Sheen",
        "password": "Password123!",
    },
    {
        "username": "andrew.cain",
        "email": "andrew.cain@example.com",
        "first_name": "Andrew",
        "last_name": "Cain",
        "password": "Password123!",
    },
    {
        "username": "livia.hodge",
        "email": "livia.hodge@example.com",
        "first_name": "Livia",
        "last_name": "Hodge",
        "password": "Password123!",
    },
    {
        "username": "callum.pace",
        "email": "callum.pace@example.com",
        "first_name": "Callum",
        "last_name": "Pace",
        "password": "Password123!",
    },
    {
        "username": "selah.frank",
        "email": "selah.frank@example.com",
        "first_name": "Selah",
        "last_name": "Frank",
        "password": "Password123!",
    },
    {
        "username": "jayden.ryle",
        "email": "jayden.ryle@example.com",
        "first_name": "Jayden",
        "last_name": "Ryle",
        "password": "Password123!",
    },
    {
        "username": "daisy.hobbs",
        "email": "daisy.hobbs@example.com",
        "first_name": "Daisy",
        "last_name": "Hobbs",
        "password": "Password123!",
    },
    {
        "username": "colin.reese",
        "email": "colin.reese@example.com",
        "first_name": "Colin",
        "last_name": "Reese",
        "password": "Password123!",
    },
    {
        "username": "ivy.cortez",
        "email": "ivy.cortez@example.com",
        "first_name": "Ivy",
        "last_name": "Cortez",
        "password": "Password123!",
    },
    {
        "username": "marcus.till",
        "email": "marcus.till@example.com",
        "first_name": "Marcus",
        "last_name": "Till",
        "password": "Password123!",
    },
    {
        "username": "ayla.moon",
        "email": "ayla.moon@example.com",
        "first_name": "Ayla",
        "last_name": "Moon",
        "password": "Password123!",
    },
]
POSTS_DATA = [
    {
        "title": "Exploring the Future of Remote Work",
        "content": "Remote work continues to evolve as technology improves and companies adopt hybrid models. Flexibility and autonomy remain key benefits for employees worldwide.",
    },
    {
        "title": "How to Stay Productive in a Digital World",
        "content": "With constant notifications and distractions, productivity requires intentional habits. Turning off alerts and creating focus blocks can drastically improve performance.",
    },
    {
        "title": "The Rise of Sustainable Fashion",
        "content": "Consumers are increasingly choosing eco-friendly brands. Recycled materials and ethical production practices are shaping the future of the fashion industry.",
    },
    {
        "title": "A Beginner’s Guide to Cloud Computing",
        "content": "Cloud computing allows organizations to scale resources efficiently. Understanding the basics of storage, servers, and security is essential for newcomers.",
    },
    {
        "title": "Healthy Eating on a Busy Schedule",
        "content": "Meal prepping, simple recipes, and smart grocery choices can make healthy eating easy even when time is limited.",
    },
    {
        "title": "Why Cybersecurity Matters More Than Ever",
        "content": "Digital threats continue to grow, impacting individuals and organizations. Strong passwords, multi-factor authentication, and regular updates are crucial defenses.",
    },
    {
        "title": "Top Travel Destinations for 2025",
        "content": "From hidden beaches to historic cities, travelers are seeking authentic experiences. Sustainable tourism remains a main consideration.",
    },
    {
        "title": "Learning a New Language Effectively",
        "content": "Immersion, consistency, and real-life practice are the pillars of successful language learning. Apps and online communities make it easier than ever.",
    },
    {
        "title": "The Importance of Mindfulness",
        "content": "Mindfulness helps reduce stress and improve emotional health. Daily routines such as breathing exercises can make a significant difference.",
    },
    {
        "title": "What Makes a Great Leader?",
        "content": "Leadership requires empathy, communication, and adaptability. Modern leaders empower teams rather than command them.",
    },
    {
        "title": "Understanding Blockchain Basics",
        "content": "Blockchain is a decentralized ledger technology that ensures transparency and security. Its applications extend far beyond cryptocurrency.",
    },
    {
        "title": "Tips for Better Sleep",
        "content": "Maintaining a regular sleep schedule and limiting screen time can greatly enhance rest quality and overall well-being.",
    },
    {
        "title": "The Art of Minimalist Living",
        "content": "Minimalism promotes reducing clutter and focusing on experiences. It encourages people to live intentionally and value what truly matters.",
    },
    {
        "title": "Getting Started With Fitness Training",
        "content": "A consistent routine, balanced workouts, and proper nutrition are the foundations of any successful fitness journey.",
    },
    {
        "title": "How AI Is Changing Education",
        "content": "Artificial intelligence is personalizing learning paths and providing students with new tools for mastering complex subjects.",
    },
    {
        "title": "The Benefits of Outdoor Activities",
        "content": "Spending time outdoors improves mood, reduces stress, and enhances physical health. Even short daily walks can make a difference.",
    },
    {
        "title": "Effective Ways to Learn Programming",
        "content": "Starting with small projects and practicing regularly helps build confidence. Online communities also provide valuable support.",
    },
    {
        "title": "Why Reading Daily Improves Your Life",
        "content": "Reading expands knowledge, improves focus, and strengthens communication skills. Even 15 minutes per day offers benefits.",
    },
    {
        "title": "Building Strong Team Collaboration",
        "content": "Open communication, trust, and clear roles help teams reach their goals efficiently. Collaborative tools also enhance productivity.",
    },
    {
        "title": "The Growth of Electric Vehicles",
        "content": "EV adoption is increasing as charging infrastructure expands and battery technology improves. Governments are also supporting the transition.",
    },
    {
        "title": "How to Set Realistic Goals",
        "content": "Breaking big goals into smaller steps makes them more manageable. Tracking progress helps maintain motivation.",
    },
    {
        "title": "Understanding Mental Health Awareness",
        "content": "Recognizing early warning signs and reducing stigma are crucial in supporting mental well-being in communities.",
    },
    {
        "title": "The Evolution of Mobile Technology",
        "content": "Smartphones continue to merge advanced photography, AI, and high-speed connectivity, becoming essential in everyday life.",
    },
    {
        "title": "Tips for Managing Personal Finances",
        "content": "Budgeting, saving, and tracking expenses help create long-term financial stability and prevent unnecessary spending.",
    },
    {
        "title": "Exploring the World of Indie Games",
        "content": "Indie developers bring creativity and innovation to the gaming industry, often delivering unique storytelling and artistic styles.",
    },
    {
        "title": "The Value of Lifelong Learning",
        "content": "Continuous learning helps individuals stay adaptable in a rapidly changing world. Online courses make education more accessible.",
    },
    {
        "title": "How Social Media Shapes Modern Culture",
        "content": "Platforms influence trends, communication, and even careers. Understanding their impact is key to responsible digital engagement.",
    },
    {
        "title": "A Guide to Starting Your First Business",
        "content": "Market research, planning, and persistence are essential for new entrepreneurs. Small steps can lead to big results.",
    },
    {
        "title": "Benefits of Working in Diverse Teams",
        "content": "Diverse perspectives lead to better problem-solving and innovation. Inclusion strengthens team performance.",
    },
    {
        "title": "How to Improve Your Communication Skills",
        "content": "Active listening, clarity, and empathy are the fundamentals of effective communication in both personal and professional life.",
    },
]
COMMENTS_DATA = [
    {"content": "Great point, I totally agree with you."},
    {"content": "I never thought about it that way before."},
    {"content": "Thanks for sharing this, really helpful!"},
    {"content": "Interesting perspective, worth considering."},
    {"content": "This explanation made things much clearer."},
    {"content": "I love how you summarized this topic."},
    {"content": "This could definitely be improved, but it’s a good start."},
    {"content": "I learned something new today, thank you."},
    {"content": "Not sure I fully agree, but it's well argued."},
    {"content": "This is exactly what I was looking for."},
    {"content": "I appreciate the level of detail you put into this."},
    {"content": "Really enjoyed reading this post."},
    {"content": "This topic deserves more attention."},
    {"content": "Could you elaborate more on this part?"},
    {"content": "Nice work—keep it up!"},
    {"content": "This gave me a lot to think about."},
    {"content": "I’m not convinced, but it's an interesting take."},
    {"content": "Very insightful, thanks!"},
    {"content": "I completely agree with your conclusion."},
    {"content": "This comment section is full of great ideas."},
    {"content": "I appreciate your honest opinion."},
    {"content": "This needs more evidence to be convincing."},
    {"content": "Thanks for putting this into simple words."},
    {"content": "This discussion is getting really interesting."},
    {"content": "Good point—never considered that before."},
    {"content": "I think you're onto something here."},
    {"content": "This deserves more visibility."},
    {"content": "Really curious to learn more about this."},
    {"content": "I like the way you explained this concept."},
    {"content": "This sparked a good conversation."},
    {"content": "I appreciate how well-written this is."},
    {"content": "I respectfully disagree with your main point."},
    {"content": "This helped clarify a misunderstanding I had."},
    {"content": "Very well explained, thank you!"},
    {"content": "This is an underrated topic."},
    {"content": "I think we need more examples here."},
    {"content": "This actually changed my mind on the subject."},
    {"content": "Your argument is solid and easy to follow."},
    {"content": "I like this idea, it has potential."},
    {"content": "Could you provide sources for this?"},
    {"content": "I didn’t expect to learn something today, but here we are."},
    {"content": "This is very inspiring, thanks!"},
    {"content": "I'm looking forward to more posts like this."},
    {"content": "This raised an important question."},
    {"content": "I appreciate the constructive tone here."},
    {"content": "Thanks for taking the time to explain this."},
    {"content": "I think this could be expanded further."},
    {"content": "Really well written, enjoyed reading it."},
    {"content": "This is a great way to look at it."},
    {"content": "I like your reasoning—it makes sense."},
    {"content": "This is more complex than I thought."},
    {"content": "I wonder how this applies in real situations."},
    {"content": "Great example, it really helps illustrate the point."},
    {"content": "This is a fresh and original take."},
    {"content": "The explanation is solid but could use more depth."},
    {"content": "I appreciate how objective this is."},
    {"content": "This aligns with what I've experienced personally."},
    {"content": "Very relevant topic, thanks for addressing it."},
    {"content": "I totally get what you're saying."},
    {"content": "This made me rethink my assumptions."},
    {"content": "I really like the direction this is going."},
    {"content": "Your perspective is appreciated."},
    {"content": "This could open up new ideas for discussion."},
    {"content": "I like the clarity of your explanation."},
    {"content": "This is something more people should read."},
    {"content": "Thanks for shedding light on this."},
    {"content": "Really thoughtful words."},
    {"content": "I see your point, but I interpret it differently."},
    {"content": "This part stood out to me the most."},
    {"content": "This helped me understand the topic better."},
    {"content": "I feel like this could go even deeper."},
    {"content": "You explained this in a very accessible way."},
    {"content": "This discussion has been enlightening."},
    {"content": "I really appreciate the insights here."},
    {"content": "This topic is more interesting than I expected."},
    {"content": "I think more examples would have helped, but good job."},
    {"content": "Great writing—keep sharing your thoughts."},
    {"content": "Very balanced and well-structured argument."},
    {"content": "This is definitely worth a second read."},
    {"content": "I didn't fully understand this at first, but now I do."},
    {"content": "Thanks for clarifying this concept."},
    {"content": "This perspective is refreshing."},
    {"content": "I think this is the best explanation I've seen so far."},
    {"content": "Your comment added a lot to the discussion."},
    {"content": "I appreciate this contribution."},
    {"content": "This is a complex topic, but you handled it well."},
    {"content": "Really enjoyed the way you expressed this idea."},
    {"content": "This brings up several important questions."},
    {"content": "Thanks for the thoughtful reply."},
    {"content": "I hope you continue posting more like this."},
]
TAGS_DATA = [
    {"name": "technology"},
    {"name": "lifestyle"},
    {"name": "travel"},
    {"name": "education"},
    {"name": "health"},
    {"name": "business"},
    {"name": "science"},
    {"name": "culture"},
    {"name": "fitness"},
    {"name": "entertainment"},
]
CATEGORIES_DATA = [
    {"name": "art"},
    {"name": "finance"},
    {"name": "food"},
    {"name": "environment"},
    {"name": "sports"},
    {"name": "history"},
    {"name": "gaming"},
    {"name": "marketing"},
    {"name": "innovation"},
    {"name": "photography"},
    {"name": "music"},
    {"name": "psychology"},
    {"name": "productivity"},
    {"name": "parenting"},
    {"name": "career"},
    {"name": "design"},
    {"name": "self-improvement"},
    {"name": "animals"},
    {"name": "news"},
    {"name": "economy"},
]
